version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo Checking Maven installation...
      - mvn --version # Debug: Verify Maven is available
  build:
    commands:
      - echo Building, Testing, and packaging the application...
      - ls -la # Debug: Check root directory
      - cd TestingApp
      - ls -la # Debug: Confirm pom.xml is here
      - mvn package -DskipTests # Build without tests
      - mvn test # Run tests for test stage
  post_build:
    commands:
      - echo Build and tests completed.
artifacts:
  files:
    - TestingApp/target/*.jar # Adjusted for subdirectory
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*' # Speed up builds